version: '3'
services:
  
  finance:
    build: ./microservice
    dns: 8.8.8.8
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://db:27017/project     
  api:
    build: ./json-api
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://db:27017/project
      - PORT=8080
      - BASE_URL=http://127.0.0.1:8080/api
      - SUFFIX_URL={ownerId}/relationships/{path}
    ports:
      - "1337:8080"
      
  db:
    image: mongo
    ports:
      - "27027:27017"
    
